import pandas

ORIG_NAMES = [
	'a01',
	'bl_bi24latitude',
	'bl_bi24longitude',
	'bl_dw15',
	'bl_dw16',
	'bl_dw19',
	'bl_dw20',
	'bl_dw21',
	'bl_dw23',
	'bl_dw25',
	'bl_dw31',
	'bl_dw32',
	'bl_dw33',
	'bl_dw34',
	'bl_dw36',
	'bl_dw39',
	'bl_dw40',
	'bl_dw41',
	'bl_dw42',
	'bl_dw44',
	'bl_dw45',
	'bl_dw46',
	'bl_dw47',
	'bl_dw52',
	'bl_dw53',
	'bl_dw54',
	'bl_dw56',
	'bl_dw57',
	'bl_dw59',
	'bl_dw61',
	'bl_dw63',
	'bl_dw64',
	'bl_dw72',
	'bl_dw73',
	'bl_sd13',
	'bl_sd14',
	'bl_sd15',
	'bl_sd24_piazza',
	'bl_sd24_leghar',
	'bl_sd26',
	'bl_sd27',
	'bl_sd28',
	'bl_sd33',
	'bl_sd35',
	'bl_sd36',
	'bl_sd43',
	'bl_sd45',
	'bl_sd46',
	'bl_sd48',
	'bl_sd49',
	'bl_sd50',
	'bl_sd51'
]


# d = Delete
# c = Continuous
# b = Binarize
# y = Turn Yes/No to 0/1
# f = Followup
# r = Regional
# o = Individual
feature_dicts = [
	{'orig_name' : 'a01', 	'new_name' : 'ID', 'mode' : 'd'},
	{'orig_name' : 'bl_bi24latitude', 'new_name' : 'lat', 'mode' : 'c'},
	{'orig_name' : 'bl_bi24longitude', 'new_name' : 'long', 'mode' : 'c'},
	{'orig_name' : 'bl_dw15', 'new_name' : 'water_source_drinking', 'mode' : 'b', 'num_values': 11},
	{'orig_name' : 'bl_dw16', 'new_name' : 'water_location_drinking', 'mode' : 'b', 'num_values': 3},
	{'orig_name' : 'bl_dw19', 'new_name' : 'water_interruptions_drinking', 'mode' : 'y'},
	{'orig_name' : 'bl_dw20', 'new_name' : 'water_unavailable', 'mode' : 'fy', 'follows_feature' : 'bl_dw19', 'follows_value' : 1},
	{'orig_name' : 'bl_dw21', 'new_name' : 'water_treated', 'mode' : 'y'},
	{'orig_name' : 'bl_dw23', 'new_name' : 'water_quality_concerns', 'mode' : 'y'},
	{'orig_name' : 'bl_dw25', 'new_name' : 'water_satisfaction', 'mode' : 'b', 'num_values': 5},
	{'orig_name' : 'bl_dw31', 'new_name' : 'water_drinking_cooking_same', 'mode' : 'y'},
	{'orig_name' : 'bl_dw32', 'new_name' : 'water_source_cooking', 'mode' : 'fb', 'follows_feature' : 'bl_dw31', 'follows_value' : 2, 'num_values': 11},
	{'orig_name' : 'bl_dw33', 'new_name' : 'water_location_cooking', 'mode' : 'fb', 'follows_feature' : 'bl_dw31', 'follows_value' : 2, 'num_values': 3},
	{'orig_name' : 'bl_dw34', 'new_name' : 'water_distance_cooking', 'mode' : 'd', 'follows_feature' : 'bl_dw33', 'follows_value' : 3},
	{'orig_name' : 'bl_dw36', 'new_name' : 'water_interruptions_cooking', 'mode' : 'fy', 'follows_feature' : 'bl_dw31', 'follows_value' : 2},
	{'orig_name' : 'bl_dw39', 'new_name' : 'toilet_type', 'mode' : 'b', 'num_values': 5},
	{'orig_name' : 'bl_dw40', 'new_name' : 'pit_latrine_depth', 'mode' : 'fb', 'follows_feature' : 'bl_dw39', 'follows_value' : 1, 'num_values': 3},
	{'orig_name' : 'bl_dw41', 'new_name' : 'toilet_shared', 'mode' : 'y'},
	{'orig_name' : 'bl_dw42', 'new_name' : 'toilet_num_households', 'mode' : 'o', 'follows_feature' : 'bl_dw41', 'follows_value' : 1},
	{'orig_name' : 'bl_dw44', 'new_name' : 'garbage_disposal', 'mode' : 'b', 'num_values': 6},
	{'orig_name' : 'bl_dw45', 'new_name' : 'garbage_distance', 'mode' : 'c'},
	{'orig_name' : 'bl_dw46', 'new_name' : 'garbage_regular', 'mode' : 'y'},
	{'orig_name' : 'bl_dw47', 'new_name' : 'garbage_frequency', 'mode' : 'fb', 'follows_feature' : 'bl_dw46', 'follows_value' : 1, 'num_values': 5},
	{'orig_name' : 'bl_dw52', 'new_name' : 'waste_water_disposal', 'mode' : 'b', 'num_values': 5},
	{'orig_name' : 'bl_dw53', 'new_name' : 'storm_drain', 'mode' : 'y'},
	{'orig_name' : 'bl_dw54', 'new_name' : 'other_drain', 'mode' : 'fy', 'follows_feature' : 'bl_dw53', 'follows_value' : 2},
	{'orig_name' : 'bl_dw56', 'new_name' : 'electricity_access', 'mode' : 'y'},
	{'orig_name' : 'bl_dw57', 'new_name' : 'electricity_source', 'mode' : 'fb', 'follows_feature' : 'bl_dw56', 'follows_value' : 1, 'num_values': 5},
	{'orig_name' : 'bl_dw59', 'new_name' : 'electricity_payment', 'mode' : 'fb', 'follows_feature' : 'bl_dw56', 'follows_value' : 1, 'num_values': 5},
	{'orig_name' : 'bl_dw61', 'new_name' : 'electricity_always', 'mode': 'fy', 'follows_feature' : 'bl_dw56', 'follows_value' : 1},
	{'orig_name' : 'bl_dw63', 'new_name' : 'electricity_interruptions', 'mode' : 'o', 'follows_feature' : 'bl_dw56', 'follows_value' : 1},
	{'orig_name' : 'bl_dw64', 'new_name' : 'electricity_outages_length', 'mode' : 'o'},
	{'orig_name' : 'bl_dw72', 'new_name' : 'lighting_source', 'mode' : 'b', 'num_values': 6},
	{'orig_name' : 'bl_dw73', 'new_name' : 'cooking_fuel', 'mode' : 'b', 'num_values': 11},
	{'orig_name' : 'bl_sd13', 'new_name' : 'road_type', 'mode' : 'b', 'num_values': 5},
	{'orig_name' : 'bl_sd14', 'new_name' : 'road_safety', 'mode' : 'c'},
	{'orig_name' : 'bl_sd15', 'new_name' : 'road_rainy_season', 'mode' : 'c'},
	{'orig_name' : 'bl_sd24_piazza', 'new_name' : 'distance_piazza', 'mode' : 'c'},
	{'orig_name' : 'bl_sd24_leghar', 'new_name' : 'distance_leghar', 'mode' : 'c'},
	{'orig_name' : 'bl_sd26', 'new_name' : 'distance_minibus', 'mode' : 'c'},
	{'orig_name' : 'bl_sd27', 'new_name' : 'distance_motorcycle', 'mode' : 'c'},
	{'orig_name' : 'bl_sd28', 'new_name' : 'distance_light_rail', 'mode' : 'c'},
	{'orig_name' : 'bl_sd33', 'new_name' : 'healthcare_used', 'mode' : 'y'},
	{'orig_name' : 'bl_sd35', 'new_name' : 'healthcare_distance', 'mode' : 'c'},
	{'orig_name' : 'bl_sd36', 'new_name' : 'healthcare_satisfaction', 'mode' : 'c', },
	{'orig_name' : 'bl_sd43', 'new_name' : 'education_used', 'mode' : 'y'},
	{'orig_name' : 'bl_sd45', 'new_name' : 'bl_sd45', 'mode' : 'c'},
	{'orig_name' : 'bl_sd46', 'new_name' : 'education_distance', 'mode' : 'o', 'follows_feature' : 'bl_sd54', 'follows_value' : -888, 'follows_logic' : 'not'},
	{'orig_name' : 'bl_sd48', 'new_name' : 'satisfaction_num_classrooms', 'mode' : 'r', 'num_values': 5},
	{'orig_name' : 'bl_sd49', 'new_name' : 'satisfaction_num_textbooks', 'mode' : 'r', 'num_values': 5},
	{'orig_name' : 'bl_sd50', 'new_name' : 'satisfaction_cost_textbooks', 'mode' : 'r', 'num_values': 5},
	{'orig_name' : 'bl_sd51', 'new_name' : 'satisfaction_education', 'mode' : 'c'}
	]




NEW_NAMES = [
	'lat',
	'long',
	'water_source_drinking',
	'water_location_drinking',
	'water_interruptions_drinking',
	'water_unavailable',
	'water_treated',
	'water_quality_concerns',
	'water_satisfaction',
	'water_drinking_cooking_same',
	'water_source_cooking',
	'water_location_cooking',
	'water_distance_cooking',
	'water_interruptions_cooking',
	'toilet_type',
	'pit_latrine_depth',
	'toilet_shared',
	'toilet_num_households',
	'garbage_disposal',
	'garbage_distance',
	'garbage_regular',
	'garbage_frequency',
	'waste_water_disposal',
	'storm_drain',
	'other_drain',
	'electricity_access',
	'electricity_source',
	'electricity_payment',
	'electricity_always',
	'electricity_interruptions',
	'electricity_outages_length',
	'lighting_source',
	'cooking_fuel',
	'road_type',
	'road_safety',
	'road_rainy_season',
	'distance_piazza',
	'distance_leghar',
	'distance_minibus',
	'distance_motorcycle',
	'distance_light_rail',
	'healthcare_used',
	'healthcare_distance',
	'healthcare_satisfaction',
	'education_used',
	'bl_sd45',
	'education_distance',
	'satisfaction_num_classrooms',
	'satisfaction_num_textbooks',
	'satisfaction_cost_textbooks',
	'satisfaction_education',
	'ID',
]